typography_spectrum: 0.58536
color:
  brandColors:
    - '#e5e6de'
    - '#764618'
    - '#cca97f'
    - '#040404'
    - '#50cecd'
  brandStrength: 0.9135841878596693
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: barrysakkers.com
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Test
    id: 07fcc78b-c94a-4c25-ac71-99756c3a9d77
    type: content
favicon: null
title: barrysakkers.com
purpose: []
