name: barrysakkers.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.58536
title: barrysakkers.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e6de'
    - '#764618'
    - '#cca97f'
    - '#040404'
    - '#50cecd'
  brandStrength: 0.9135841878596693
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
